### ISSUE TITLE
Apps targeted as maximum for 9.0 do not show for 8.2

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/appstore-issues#39]
When setting "Maximum required" to 9.0 at https://apps.owncloud.com/content/show.php?content=164356 the response from https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922&approved=all does not show it. (search for "Tasks")

When setting it to 9.1 it is however displayed. Seems like a bug.

@karlitschek FYI

**Comment by ghost** [comment]
Seems this is currently also happening for the documents app also having a max version of 9.0:

https://apps.owncloud.com/content/show.php/Documents?content=168711

**Comment by anomaly256** [comment]
I'm having the issue wrt the Documents app not appearing on 8.2.2

**Comment by RockScience** [comment]
Same issue here. Thank you RealRancor for referencing.

**Comment by karlitschek** [comment]
should be fixed now.

**Comment by ghost** [comment]
@karlitschek Is there any caching in place? The documents app is still not showing up at https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922&approved=all

**Comment by ghost** [comment]
Ok, seems its unrelated to that issue. The tasks app is still showing up with "Maximum required   ownCloud 9.0" so there seems to be an issue somewhere in the documents app.
